apiVersion: v1
kind: Service
metadata:
  name: devops-demo-app
  namespace: devops-demo
  labels:
    app: devops-demo-app
spec:
  # Selector matches Pods with this label - routing traffic to pods
  selector:
    app: devops-demo-app
  ports:
    - name: http
    # Port on which the Service is accessibe within the cluster
      port: 80
    # Port on which the container is listening 
      targetPort: 5000
      protocol: TCP
    # ClusterIP - Service is only accessible within the cluster
    # Maybe add LoadBalancer in the future, currently part of k3d infra
  type: ClusterIP
